stages:
  - linting
  - test

before_script:
  - pip install --upgrade pip
  - pip3 install -r requirements/prod.txt
  - pip3 install -r requirements/dev.txt
  - pip3 install -r requirements/test.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install pep8-naming flake8-import-order flake8-quotes flake8-absolute-import flake8-builtins
    - pip install flake8-commas flake8-comments flake8-comprehensions flake8-eradicate
    - pip install flake8-fixme flake8-print flake8-type-ignore
    - flake8 lyceum

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --line-length 79 --check lyceum

test:
  stage: test
  image: python:3.12
  script:
    - cd lyceum
    - python3 manage.py test