stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install pep8-naming flake8-import-order flake8-quotes
    - flake8 --exclude venv lyceum --inline-quotes double

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check lyceum

mypy:
  stage: linting
  image: python:latest
  script:
    - pip install mypy
    - pip install python-dotenv
    - pip install django-stubs==1.12.0
    - pip install django-stubs-ext==4.2.7
    - mypy --verbose lyceum
