stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose

black:
  stage: linting
  image: python:3.12
  script:
    - black --check .

