stages:
  - linting
  - refactoring

before_script:
  - pip install -r requirements/dev.txt
  - pip install -r requirements/test.txt
  - pip install -r requirements/prod.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --inline-quotes double .

black:
  stage: refactoring
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

mypy:
  stage: linting
  image: registry.gitlab.com/pipeline-components/mypy:latest
  script:
   - pip install mypy
   - mypy --verbose .

