stages:
  - linting

before_script:
  - pip install -r requirements/dev.txt

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --inline-quotes double .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --config pyproject.toml .
    - black --check .
