# Generated by Django 4.2 on 2024-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmodel",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="имя"
            ),
        ),
    ]
