# Generated by Django 4.2 on 2024-03-20 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_feedbackmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("work", "Work"),
                    ("ans", "Answered"),
                ],
                default="new",
                max_length=4,
                verbose_name="статус",
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("work", "Work"),
                            ("ans", "Answered"),
                        ],
                        db_column="from",
                        default="new",
                        max_length=4,
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("work", "Work"),
                            ("ans", "Answered"),
                        ],
                        default="new",
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
