# Generated by Django 4.2 on 2024-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedbackmodel_status_statuslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="почта"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("job", "Work"),
                            ("ans", "Answered"),
                        ],
                        default="new",
                        max_length=3,
                        verbose_name="статус",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FeedbackModel",
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                choices=[("new", "New"), ("job", "Work"), ("ans", "Answered")],
                db_column="from",
                default="new",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[("new", "New"), ("job", "Work"), ("ans", "Answered")],
                default="new",
                max_length=3,
            ),
        ),
    ]
