# Generated by Django 4.2 on 2024-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_delete_feedbackmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("wip", "Work in progress"),
                    ("ans", "Answered"),
                ],
                default="new",
                max_length=3,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("wip", "Work in progress"),
                    ("ans", "Answered"),
                ],
                db_column="from",
                default="new",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("wip", "Work in progress"),
                    ("ans", "Answered"),
                ],
                default="new",
                max_length=3,
            ),
        ),
    ]
