# Generated by Django 4.2 on 2024-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_feedback_status_alter_statuslog_from_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                default="", max_length=100, verbose_name="имя"
            ),
        ),
    ]
