# Generated by Django 4.2 on 2024-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_feedback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
    ]
