# Generated by Django 4.2 on 2024-03-25 01:30

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0015_alter_user_email"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
