# Generated by Django 4.2 on 2024-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество попыток входа",
                verbose_name="попыток входа",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="freeze_date",
            field=models.DateTimeField(
                blank=True,
                help_text="дата заморозки",
                null=True,
                verbose_name="дата заморозки",
            ),
        ),
    ]
