# Generated by Django 4.2 on 2024-02-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_imagemodel_options_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="catalog/",
                        verbose_name="главное изображение",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "default_related_name": "main_image",
            },
        ),
        migrations.DeleteModel(
            name="ImageModel",
        ),
    ]
