# Generated by Django 4.2 on 2024-02-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_mainimage_delete_imagemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "default_related_name": "categories",
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="catalog.tag"
            ),
        ),
    ]
