# Generated by Django 4.2 on 2024-02-29 20:12

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Введите описание объекта",
                validators=[
                    catalog.validators.WordsValidator("превосходно", "роскошно")
                ],
                verbose_name="описание",
            ),
        ),
    ]
