# Generated by Django 4.2 on 2024-03-06 19:42

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0006_alter_category_options_alter_mainimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                default=None,
                upload_to=catalog.models.item_directory_path,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.DeleteModel(
            name="GalleryImage",
        ),
    ]
