# Generated by Django 4.2 on 2024-03-15 15:53

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_item_created_item_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Максимальное значение - 32767",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Значение должно быть больше 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        32767,
                        message="Значение должно быть меньше 32767",
                    ),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="item",
            field=models.ForeignKey(
                help_text="Добавьте больше фотографий, относящихся к товару",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Описание должно содержать слова 'превосходно' или 'роскошно'.",
                validators=[
                    catalog.validators.WordsValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                help_text="Главное изображение товара (будет отображаться в списке товаров)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
            ),
        ),
    ]
